### ISSUE TITLE
Library usage

### ISSUE THREAD

**Issue by bennyn** [kamilmielnik/scrabble-solver#1]
Hello, can I use this package as a library that helps me solving scrabbles just by giving it input characters? 

What I want to build is something like this: http://www.scrabble-solver.com/

The idea is to use it the following way:

```js
const scrabbleSolver = require('scrabble-solver');
const input = ['A', 'B', 'S', 'C', 'U', 'V', 'W', 'I', 'J'];
const language = 'en';
const results = scrabbleSolver(input, language); // ["AB", "ABS", "AS", "BA", "BAC", "BACS", "BAS", "BUS", "CAB", "CABS", "CUB", "CUBS", "SAB", "SAC", "SAU", "SAV", "SCAB", "SCUBA", "SCUBA", "SUB", "SUBA", "US", "UVA", "UVAS", "VAC", "VACS", "VAS", "VAU", "VAUS"]
```

**Comment by kamilmielnik** [comment]
Hello,

Not exactly. Please see this file: https://github.com/
kamilmielnik/scrabble-solver/blob/master/scrabble-solver-
backend/src/solver/index.js

The `solve` function requires a `Board` instance and an array of `Tiles`.
You would need to prepare both.

`Tiles` are pretty straightforward, you just need to create instances of
`Tile` model (
https://github.com/kamilmielnik/scrabble-solver/blob/master/scrabble-solver-commons/models/tile.js)
based on your characters (letters).

`Board` would require some trickery. You could create a board that only has
1 row and 7 columns. To see how to do that, you can check the unit tests.

I think that this file contains all the code you need:
https://github.com/kamilmielnik/scrabble-solver/blob/master/scrabble-solver-backend/src/solver/__tests__/index.test.js

Please check the license before using this library though.

To automatically download & prepare dictionaries just download the
repository and run `npm install`.


13.02.2018 11:23 PM "Benny Neugebauer" <notifications@github.com>
napisał(a):

Hello, can I use this package as a library that helps me solving scrabbles
just by giving it input characters?

What I want to build is something like this: http://www.scrabble-solver.com/

The idea is to use it the following way:

const scrabbleSolver = require('scrabble-solver');const input = ['A',
'B', 'S', 'C', 'U', 'V', 'W', 'I', 'J'];const language = 'en';const
results = scrabbleSolver(input, language); // ["AB", "ABS", "AS",
"BA", "BAC", "BACS", "BAS", "BUS", "CAB", "CABS", "CUB", "CUBS",
"SAB", "SAC", "SAU", "SAV", "SCAB", "SCUBA", "SCUBA", "SUB", "SUBA",
"US", "UVA", "UVAS", "VAC", "VACS", "VAS", "VAU", "VAUS"]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kamilmielnik/scrabble-solver/issues/1>, or mute the
thread

**Comment by kamilmielnik** [comment]
Hello @bennycode !

FYI what you asked about is now possible. Sorry for 3-year delay!

Here's an example:

```js
import { Trie } from '@kamilmielnik/trie';
import { scrabble } from '@scrabble-solver/configs';
import { BLANK } from '@scrabble-solver/constants';
import { Board, Cell, Config, Tile } from '@scrabble-solver/models';
import Solver from '@scrabble-solver/solver';

// When board is empty, solver tries to find a word that crosses the center of the board.
// This will produce "duplicated" results if you're not interested in board-aware results,
// as a N-letter word can be placed on empty board in 2*N ways.
// So we fake the board to have a single row and the center in the corner to eliminate
// all those extra permutations :)

const BOARD_HEIGHT = 1;

class FakeBoard extends Board {
  static fromJson(json) {
    return new FakeBoard({
      board: json.map((row) => row.map(Cell.fromJson)),
    });
  }

  get center() {
    return this.board[0][0];
  }
}

class FakeConfig extends Config {
  static fromJson(json) {
    return new FakeConfig(json);
  }

  get boardHeight() {
    return 1;
  }
}

function getResults(dictionary, characters, language) {
  const trie = Trie.fromArray(dictionary);
  const config = FakeConfig.fromJson(scrabble[language].toJson());
  const tiles = characters.map((character) => {
    return new Tile({
      character: character.toLowerCase(),
      isBlank: character === BLANK,
    });
  });
  const solver = new Solver(config, trie);
  const originalBoard = Board.create(config.boardWidth, config.boardHeight);
  console.log(config.boardWidth, config.boardHeight);
  const board = FakeBoard.fromJson(originalBoard.toJson());
  return solver.solve(board, tiles);
}

/////////////////////////////////////////

const dictionary = [
  // Just load dictionary as an array of strings, you can use this SOWPODS dictionary:
  // https://www.wordgamedictionary.com/sowpods/download/sowpods.txt
  'apple',
  'bicycle',
  'car',
  'bus',
];
const characters = ['A', 'B', 'S', 'C', 'U', 'V', 'W', 'I', 'J']; // use space ' ' for blanks
const language = 'en-US'; // 'en-GB' and 'pl-PL' also supported

const results = getResults(dictionary, characters, language);

console.log(`Results count: ${results.length}`);
```
