### ISSUE TITLE
Valid word is not offered as a solution ( language : română )

### ISSUE THREAD

**Issue by cristian-po** [kamilmielnik/scrabble-solver#313]
Game: Scrabble
Language: Română
Word not found: FOISI   Points:  40

See below captures.

![IMG_3064](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/9257a68a-2c68-434c-97c9-57efdd363f9a)
![IMG_3065](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/73f15d07-398e-4743-b2ea-7c7cf47fcce6)

Maybe the dictionary is not fully loaded or there is a typing error in the dictionary file.

**Comment by kamilmielnik** [comment]
Thank you for the report @cristian-po !

Fixed with 0cb0eaf6ce9e9f8f0c92f4f833550d237a659a4a. I released a new version and updated scrabble-solver.org just now.
The dictionaries are cached up to 24 hours, so there might be a delay before you see the change.
If you don't want to wait you will need to manually [unregister service workers in the app via browser developer tools](https://github.com/kamilmielnik/scrabble-solver/assets/6830683/25edc0ad-0da5-4131-902c-c0a7e2c9c192).
